### ISSUE TITLE
Generic's for "getByFqn" function

### ISSUE THREAD

**Issue by nusje2000** [aeviiq/factory#9]
It would be nice to have a @template annotation for the getByFqn function so static code analysis tools like php-stan will understand the return type. A simple annotation like this will do the job:
```
/**
 * @template T
 * @param class-string<T> $fqn
 *
 * @return T
 * @throws LogicException
 */
```

**Comment by aeviiq** [comment]
Solved in https://github.com/aeviiq/factory/pull/10
